-- Egyptian food macro seed data from user-provided approximate macro table.
-- These values are practical fitness estimates, not medical-grade nutrition data.
insert into public.food_items (food_name, serving_size, calories, protein_g, carbs_g, fat_g, category, cuisine, source_type, is_global, aliases)
values
  ('Molokhia', '1 bowl', 180, 5, 12, 12, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['molokhia']),
  ('White rice', '1 cup cooked', 260, 5, 52, 4, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['white rice']),
  ('Rice with vermicelli', '1 cup', 300, 6, 55, 7, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['rice with vermicelli']),
  ('Baladi bread', '1 medium loaf', 300, 9, 60, 2, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['baladi bread']),
  ('Half baladi bread', '1/2 loaf', 150, 4.5, 30, 1, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['half baladi bread']),
  ('Quarter baladi bread', '1/4 loaf', 75, 2, 15, 0.5, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['quarter baladi bread']),
  ('Boiled egg', '1 egg', 75, 6, 1, 5, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['boiled egg']),
  ('Fried egg', '1 egg', 110, 6, 1, 8, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fried egg']),
  ('Omelette', '2 eggs', 220, 13, 2, 17, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['omelette']),
  ('Shakshuka', '1 plate', 320, 18, 15, 22, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['shakshuka']),
  ('Ful medames', '1 cup', 280, 17, 45, 4, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['ful medames']),
  ('Ful with oil', '1 cup + oil', 380, 17, 45, 15, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['ful with oil']),
  ('Ful sandwich', '1 sandwich', 430, 18, 70, 8, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['ful sandwich']),
  ('Taameya / falafel', '1 piece', 90, 3, 8, 5, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['taameya falafel']),
  ('Taameya sandwich', '1 sandwich', 500, 16, 65, 20, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['taameya sandwich']),
  ('Besara', '1 bowl', 320, 20, 42, 9, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['besara']),
  ('Lentil soup', '1 bowl', 280, 15, 40, 7, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['lentil soup']),
  ('Black lentils / ads be gebba', '1 cup', 300, 18, 45, 6, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['black lentils ads be gebba']),
  ('Koshary', '1 medium bowl', 750, 22, 120, 20, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['koshary']),
  ('Koshary small', '1 small bowl', 500, 15, 85, 13, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['koshary small']),
  ('Red pasta sauce', '1/2 cup', 90, 2, 12, 4, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['red pasta sauce']),
  ('Pasta with red sauce', '1 plate', 500, 14, 85, 12, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['pasta with red sauce']),
  ('Plain pasta', '1 cup cooked', 220, 8, 43, 1, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['plain pasta']),
  ('Macarona bechamel', '1 slice', 650, 28, 55, 35, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['macarona bechamel']),
  ('Bechamel sauce', '1/2 cup', 180, 5, 15, 11, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['bechamel sauce']),
  ('Egyptian potato stew', '1 bowl', 300, 6, 42, 12, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['egyptian potato stew']),
  ('Fried potatoes', '1 plate', 450, 6, 55, 22, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fried potatoes']),
  ('Air-fryer potatoes', '1 plate', 250, 5, 45, 5, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['air-fryer potatoes']),
  ('Potato sandwich', '1 sandwich', 520, 10, 65, 22, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['potato sandwich']),
  ('Mashed potatoes', '1 plate', 320, 6, 45, 12, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mashed potatoes']),
  ('Mahshi rice filling', '1 cup', 330, 6, 55, 10, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mahshi rice filling']),
  ('Mahshi warak enab', '10 pieces', 420, 8, 65, 14, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mahshi warak enab']),
  ('Mahshi kousa', '4 pieces', 380, 10, 55, 13, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mahshi kousa']),
  ('Mahshi kromb', '6 rolls', 430, 11, 62, 15, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mahshi kromb']),
  ('Mahshi eggplant', '4 pieces', 400, 9, 55, 15, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['mahshi eggplant']),
  ('Roasted eggplant', '1 medium', 120, 3, 25, 1, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roasted eggplant']),
  ('Fried eggplant', '1 plate', 350, 5, 25, 25, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fried eggplant']),
  ('Baba ghanoush', '1/2 cup', 130, 3, 10, 9, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['baba ghanoush']),
  ('Tehina salad', '1/4 cup', 180, 5, 6, 16, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['tehina salad']),
  ('Egyptian salad', '1 bowl', 80, 3, 14, 2, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['egyptian salad']),
  ('Pickles', '1 small plate', 30, 1, 6, 0, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['pickles']),
  ('Cucumber yogurt salad', '1 bowl', 120, 6, 10, 6, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['cucumber yogurt salad']),
  ('Moussaka Egyptian style', '1 plate', 430, 14, 25, 30, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['moussaka egyptian style']),
  ('Bamya', '1 bowl', 220, 6, 22, 12, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['bamya']),
  ('Peas and carrots stew', '1 bowl', 260, 8, 35, 10, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['peas and carrots stew']),
  ('White beans stew', '1 bowl', 330, 15, 45, 9, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['white beans stew']),
  ('Green beans stew', '1 bowl', 220, 7, 25, 10, 'Legumes', 'Egyptian', 'user_provided_approximate_macro_table', true, array['green beans stew']),
  ('Torly vegetables', '1 plate', 250, 7, 30, 11, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['torly vegetables']),
  ('Spinach stew', '1 bowl', 210, 8, 20, 10, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['spinach stew']),
  ('Zucchini stew', '1 bowl', 190, 5, 18, 11, 'Vegetable dish', 'Egyptian', 'user_provided_approximate_macro_table', true, array['zucchini stew']),
  ('Grilled chicken breast', '150 g', 250, 45, 0, 6, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['grilled chicken breast']),
  ('Grilled chicken thigh', '1 piece', 280, 28, 0, 18, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['grilled chicken thigh']),
  ('Boiled chicken breast', '150 g', 240, 45, 0, 5, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['boiled chicken breast']),
  ('Roasted chicken quarter', '1 quarter', 380, 42, 0, 22, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roasted chicken quarter']),
  ('Chicken pane', '1 piece', 450, 35, 25, 24, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['chicken pane']),
  ('Chicken shawarma meat', '150 g', 360, 38, 5, 20, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['chicken shawarma meat']),
  ('Chicken kofta', '150 g', 320, 32, 8, 18, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['chicken kofta']),
  ('Grilled beef kofta', '150 g', 400, 30, 5, 28, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['grilled beef kofta']),
  ('Beef kebab', '150 g', 380, 36, 2, 25, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['beef kebab']),
  ('Beef cubes / kabab halla', '150 g', 360, 34, 5, 24, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['beef cubes kabab halla']),
  ('Minced beef cooked', '150 g', 375, 32, 0, 27, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['minced beef cooked']),
  ('Beef shawarma meat', '150 g', 420, 32, 5, 30, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['beef shawarma meat']),
  ('Alexandrian liver', '150 g', 360, 30, 10, 22, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['alexandrian liver']),
  ('Sogo'' baladi', '150 g', 420, 21, 7, 35, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sogo'' baladi']),
  ('Hawawshi', '1 piece', 650, 32, 55, 32, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['hawawshi']),
  ('Burger patty Egyptian style', '150 g', 390, 28, 6, 28, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['burger patty egyptian style']),
  ('Grilled fish', '1 medium fish', 350, 45, 0, 18, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['grilled fish']),
  ('Fried fish', '1 medium fish', 520, 42, 20, 30, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fried fish']),
  ('Tuna', '1 can drained', 180, 30, 0, 6, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['tuna']),
  ('Tuna sandwich', '1 sandwich', 420, 28, 45, 14, 'Protein', 'Egyptian', 'user_provided_approximate_macro_table', true, array['tuna sandwich']),
  ('Shrimp grilled', '150 g', 180, 35, 2, 3, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['shrimp grilled']),
  ('Fried shrimp', '150 g', 380, 30, 25, 18, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fried shrimp']),
  ('Sayadeya rice', '1 cup', 350, 7, 60, 10, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sayadeya rice']),
  ('Fatta rice', '1 cup', 330, 6, 55, 9, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['fatta rice']),
  ('Crispy bread for fatta', '1 cup', 220, 6, 40, 5, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['crispy bread for fatta']),
  ('Garlic vinegar sauce', '1/4 cup', 70, 1, 8, 4, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['garlic vinegar sauce']),
  ('Roz me''ammar', '1 portion', 520, 12, 65, 24, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roz me''ammar']),
  ('Feteer meshaltet', '1 medium piece', 700, 12, 75, 38, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['feteer meshaltet']),
  ('Feteer with cheese', '1 portion', 850, 25, 80, 48, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['feteer with cheese']),
  ('Feteer with honey', '1 portion', 780, 12, 105, 34, 'Carbohydrate staple', 'Egyptian', 'user_provided_approximate_macro_table', true, array['feteer with honey']),
  ('Sambosa cheese', '1 piece', 100, 3, 9, 6, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sambosa cheese']),
  ('Sambosa meat', '1 piece', 120, 5, 9, 7, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sambosa meat']),
  ('Roumy cheese', '50 g', 180, 12, 1, 14, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roumy cheese']),
  ('White cheese / gebna beda', '50 g', 130, 8, 2, 10, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['white cheese gebna beda']),
  ('Cottage cheese / areesh', '100 g', 110, 18, 4, 2, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['cottage cheese areesh']),
  ('Cheese tomato sandwich', '1 sandwich', 380, 15, 45, 16, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['cheese tomato sandwich']),
  ('Roumy cheese sandwich', '1 sandwich', 480, 20, 45, 24, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roumy cheese sandwich']),
  ('Yogurt small cup', '1 cup', 100, 6, 10, 4, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['yogurt small cup']),
  ('Greek yogurt', '1 cup', 150, 20, 8, 4, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['greek yogurt']),
  ('Milk', '1 cup', 120, 8, 12, 5, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['milk']),
  ('Tea with milk', '1 cup', 80, 4, 8, 3, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['tea with milk']),
  ('Nescafe with milk', '1 cup', 90, 5, 10, 3, 'Dairy', 'Egyptian', 'user_provided_approximate_macro_table', true, array['nescafe with milk']),
  ('Sugar cane juice', '1 cup', 180, 0, 45, 0, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sugar cane juice']),
  ('Hibiscus / karkade sweetened', '1 cup', 120, 0, 30, 0, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['hibiscus karkade sweetened']),
  ('Sahlab', '1 cup', 280, 8, 45, 8, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['sahlab']),
  ('Roz bel laban', '1 bowl', 350, 9, 55, 10, 'Dessert or drink', 'Egyptian', 'user_provided_approximate_macro_table', true, array['roz bel laban']),
  ('Om Ali', '1 bowl', 600, 12, 65, 34, 'Egyptian food', 'Egyptian', 'user_provided_approximate_macro_table', true, array['om ali']),
  ('Basbousa', '1 piece', 300, 5, 45, 12, 'Dessert or drink', 'Egyptian', 'user_provided_approximate_macro_table', true, array['basbousa']),
  ('Konafa', '1 piece', 420, 6, 55, 22, 'Dessert or drink', 'Egyptian', 'user_provided_approximate_macro_table', true, array['konafa']),
  ('Zalabya / loqmet el qady', '5 pieces', 350, 4, 55, 14, 'Dessert or drink', 'Egyptian', 'user_provided_approximate_macro_table', true, array['zalabya loqmet el qady'])
on conflict on constraint food_items_unique_source do update set
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  category = excluded.category,
  cuisine = excluded.cuisine,
  aliases = excluded.aliases,
  updated_at = now();
